import { Theme, webLightTheme } from '@fluentui/react-components';

export const brandATheme: Theme = {
  ...webLightTheme,
  spacingHorizontalMNudge: '12px',
  spacingHorizontalM: '16px',
  spacingHorizontalL: '24px',
  spacingHorizontalXL: '32px',
  spacingHorizontalXXL: '48px',
  spacingHorizontalXXXL: '64px',
  spacingVerticalMNudge: '12px',
  spacingVerticalM: '16px',
  spacingVerticalL: '24px',
  spacingVerticalXL: '32px',
  spacingVerticalXXL: '48px',
  spacingVerticalXXXL: '64px',
  strokeWidthThin: '1px solid',
  strokeWidthThick: '2px solid',
  strokeWidthThicker: '3px solid',
  strokeWidthThickest: '4px solid',
  shadow2: '0 0 2px rgba(0,0,0,0.14), 0 1px 2px rgba(0,0,0,0.12)',
  colorNeutralForeground2BrandHover: '#0047a0',
  colorNeutralForeground2BrandPressed: '#003e8b',
  colorNeutralForeground2BrandSelected: '#0047a0',
  colorNeutralForeground3BrandHover: '#0047a0',
  colorNeutralForeground3BrandPressed: '#003e8b',
  colorNeutralForeground3BrandSelected: '#0047a0',
  colorBrandForegroundLink: '#003e8b',
  colorBrandForegroundLinkHover: '#003b84',
  colorBrandForegroundLinkPressed: '#003476',
  colorBrandForegroundLinkSelected: '#003e8b',
  colorCompoundBrandForeground1: '#0047a0',
  colorCompoundBrandForeground1Hover: '#003e8b',
  colorCompoundBrandForeground1Pressed: '#003b84',
  colorBrandForeground1: '#0047a0',
  colorBrandForeground2: '#003e8b',
  colorBrandForegroundInverted: '#306ab2',
  colorBrandForegroundInvertedHover: '#487cbb',
  colorBrandForegroundInvertedPressed: '#306ab2',
  colorBrandForegroundOnLight: '#0047a0',
  colorBrandForegroundOnLightHover: '#003e8b',
  colorBrandForegroundOnLightPressed: '#00387d',
  colorBrandForegroundOnLightSelected: '#003b84',
  colorBackgroundOverlay: 'rgba(0, 0, 0, 0.1)',
  colorBrandBackground: '#0047a0',
  colorBrandBackgroundHover: '#003e8b',
  colorBrandBackgroundPressed: '#003476',
  colorBrandBackgroundSelected: '#003b84',
  colorCompoundBrandBackground: '#0047a0',
  colorCompoundBrandBackgroundHover: '#003e8b',
  colorCompoundBrandBackgroundPressed: '#003b84',
  colorBrandBackgroundStatic: '#0047a0',
  colorBrandBackground2: '#f1f6fb',
  colorBrandBackgroundInvertedHover: '#f1f6fb',
  colorBrandBackgroundInvertedPressed: '#91b0d7',
  colorBrandBackgroundInvertedSelected: '#a9c2e0',
  colorNeutralStrokeAccessibleSelected: '#0047a0',
  colorBrandStroke1: '#0047a0',
  colorBrandStroke2: '#91b0d7',
  colorCompoundBrandStroke: '#0047a0',
  colorCompoundBrandStrokeHover: '#003e8b',
  colorCompoundBrandStrokePressed: '#003b84',
  colorNeutralShadowAmbient: 'rgba(0, 0, 0, 0.12)',
  colorNeutralShadowKey: 'rgba(0, 0, 0, 0.14)',
  colorNeutralShadowAmbientLighter: 'rgba(0, 0, 0, 0.06)',
  colorNeutralShadowKeyLighter: 'rgba(0, 0, 0, 0.07)',
  colorNeutralShadowAmbientDarker: 'rgba(0, 0, 0, 0.2)',
  colorNeutralShadowKeyDarker: 'rgba(0, 0, 0, 0.24)',
  colorBrandShadowAmbient: 'rgba(0, 0, 0, 0.3)',
  colorBrandShadowKey: 'rgba(0, 0, 0, 0.25)'
};
