name: Credit Top-up Pipeline

on:
  workflow_dispatch:

env:
  DOCKERFILE: "${{ env.GITHUB_WORKSPACE }}/cmd/credit-topup/Dockerfile"

jobs:
  build-and-push:
    name: Build and Push
    steps:
      - name: Show values
        run: echo '${{ env.GITHUB_WORKSPACE }}'
      - name: Show values
        run: echo "$DOCKERFILE"