name: Credit Top-up Pipeline

on:
  workflow_dispatch:

env:
  DOCKERFILE: "${{ github.workspace }}/cmd/credit-topup/Dockerfile"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Show values
        run: echo "$DOCKERFILE"