name: Generate Themes On Project Changes

on:
  push:
    branches:
      - 'master'
    paths:
      - 'tokens/**.json'

jobs:

  generate_themes:
    name: Generate Themes
    runs-on: ubuntu-20.04
    container:
      image: node:18.14.2-alpine
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run generate-themes