name: Generate Themes On Project Changes

on:
  push:
    branches:
      - 'master'
    paths:
      - 'tokens/**.json'

jobs:

  generate_themes:
    name: Generate Themes
    runs-on: ubuntu-20.04
    container:
      image: node:18.14.2-alpine
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Generate themes
        run: npm run generate-themes
      - name: Logging
        run: ls src/themes
      - name: Ensure git is present
        run: RUN apk add --no-cache git
      - name: Commit generated themes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Automated update of themes on token change'