name: Generate Themes On Project Changes

on:
  push:
    branches:
      - 'master'
    paths:
      - 'tokens/**.json'

jobs:

  generate_themes:
    name: Generate Themes
    runs-on: ubuntu-20.04
    container:
      image: node: 18.14.2
    steps:
     - run: npm ci
     - run: echo "done"